"""Initial schema

Revision ID: 864ea9a4e248
Revises: 
Create Date: 2026-09-10 06:07:55.947657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '864ea9a4e248'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_dna_cache',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('cache_key', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=50), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('template_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('slides', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cache_key')
    )
    op.create_index('idx_deck_dna_dept', 'deck_dna_cache', ['department'], unique=False)
    op.create_index('idx_deck_dna_expires', 'deck_dna_cache', ['expires_at'], unique=False)
    op.create_table('governance_changes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('gate_id', sa.String(length=255), nullable=True),
    sa.Column('approver', sa.String(length=255), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('mycelium_edges', 'weight',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_constraint(op.f('mycelium_edges_from_kr_to_kr_key'), 'mycelium_edges', type_='unique')
    op.create_unique_constraint('uq_edge_from_to', 'mycelium_edges', ['from_kr', 'to_kr'])
    op.drop_constraint(op.f('sentinel_gate_evidence_gate_request_id_experience_id_signer_key'), 'sentinel_gate_evidence', type_='unique')
    op.create_unique_constraint('uq_gate_evidence', 'sentinel_gate_evidence', ['gate_request_id', 'experience_id', 'signer'])
    op.alter_column('synapsis_evidence', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_interpretations', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_learning', 'outcome_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_learning', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_outcomes', 'outcome_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_outcomes', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('synapsis_outputs', 'confidence',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('synapsis_outputs', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_outcomes', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_outcomes', 'outcome_score',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_learning', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_learning', 'outcome_score',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_interpretations', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.alter_column('synapsis_evidence', 'confidence',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_constraint('uq_gate_evidence', 'sentinel_gate_evidence', type_='unique')
    op.create_unique_constraint(op.f('sentinel_gate_evidence_gate_request_id_experience_id_signer_key'), 'sentinel_gate_evidence', ['gate_request_id', 'experience_id', 'signer'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uq_edge_from_to', 'mycelium_edges', type_='unique')
    op.create_unique_constraint(op.f('mycelium_edges_from_kr_to_kr_key'), 'mycelium_edges', ['from_kr', 'to_kr'], postgresql_nulls_not_distinct=False)
    op.alter_column('mycelium_edges', 'weight',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text('0.0'))
    op.drop_table('governance_changes')
    op.drop_index('idx_deck_dna_expires', table_name='deck_dna_cache')
    op.drop_index('idx_deck_dna_dept', table_name='deck_dna_cache')
    op.drop_table('deck_dna_cache')
    # ### end Alembic commands ###
